
package base_package.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Dec 15 15:04:48 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "getHello", namespace = "http://base_package/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getHello", namespace = "http://base_package/")

public class GetHello {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

