
package base_package.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Dec 15 15:04:48 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "getHelloResponse", namespace = "http://base_package/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getHelloResponse", namespace = "http://base_package/")

public class GetHelloResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

