
package mayia20thsoapcxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Jan 05 10:44:25 IST 2018
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "additionResponse", namespace = "http://mayia20thsoapcxf/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "additionResponse", namespace = "http://mayia20thsoapcxf/")

public class AdditionResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

