
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri.areaservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-01-29T22:54:17.485+05:30
 * Generated source version: 3.0.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "AreaService",
                      portName = "AreaServiceSOAP",
                      targetNamespace = "http://tempuri.org/AreaService/",
                      wsdlLocation = "file:/C:/Users/M1043173/AreaProj/WebContent/AreaService.wsdl",
                      endpointInterface = "org.tempuri.areaservice.AreaService")
                      
public class AreaServiceSOAPImpl implements AreaService {

    private static final Logger LOG = Logger.getLogger(AreaServiceSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.areaservice.AreaService#calculateRectArea(org.tempuri.areaservice.Dimensions parameters)*
     */
    public float calculateRectArea(Dimensions parameters) { 
        LOG.info("Executing operation calculateRectArea");
        System.out.println(parameters);
        try {
            float _return = 0.24852568f;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
