
package last.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Dec 15 09:09:14 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "helloResponse", namespace = "http://last/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "helloResponse", namespace = "http://last/")

public class HelloResponse {


}

