
package apache_soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Fri Dec 15 08:46:12 IST 2017
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "getHelloWorld", namespace = "http://apache_soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getHelloWorld", namespace = "http://apache_soap/")

public class GetHelloWorld {


}

