<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AddService" targetNamespace="http://com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://com/" schemaLocation="add_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="addResponse">
    <wsdl:part name="parameters" element="tns:addResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="add">
    <wsdl:part name="parameters" element="tns:add">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Add">
    <wsdl:operation name="add">
      <wsdl:input name="add" message="tns:add">
    </wsdl:input>
      <wsdl:output name="addResponse" message="tns:addResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AddServiceSoapBinding" type="tns:Add">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="add">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="add">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="addResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AddService">
    <wsdl:port name="AddPort" binding="tns:AddServiceSoapBinding">
      <soap:address location="http://localhost:8086/SoapCfx/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
